services:
  pgsql-api-agendamento:
    image: postgres:alpine
    ports:
      - "5456:5432"
    container_name: "pgsql-api-agendamento"
    restart: always
    volumes:
      - data-api-agendamento:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-api_agendamento_db}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
volumes:
  data-api-agendamento: