quarkus.datasource.jdbc.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5456}/${POSTGRES_DB:app_database}
%dev.quarkus.datasource.username=${POSTGRES_USER:postgres}
%dev.quarkus.datasource.password=${POSTGRES_PASSWORD:postgres}
%dev.quarkus.hibernate-orm.database.generation=update
# Usar para validação de dados a serem inseridos em modo DEV
# quarkus.hibernate-orm.log.sql=true
# quarkus.hibernate-orm.log.bind-parameters=true